default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Bhartee@123
  host: localhost
  port: 5432

development:
  <<: *default
  database: shortned_app
  username: postgres
  password: Bhartee@123

